version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.1.0

jobs:
  deploy_cloud_function:
    working_directory: ~/
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: "Update secrets"
          command: |
            PROJECT_ID=$GOOGLE_PROJECT_ID\
              WRITE_SECRET=$WRITE_SECRET\
              READ_ONLY_SECRET=$READ_ONLY_SECRET\
              make update_secrets
      - run:
          name: "Deploy Cloud Function"
          command: |
            PROJECT_ID=$GOOGLE_PROJECT_ID make deploy_to_gfunctions

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_cloud_function:
          context:
            - iamevan-me/gcp
          filters:
             branches:
               only: master
