version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.1.0

jobs:
  build:
    working_directory: ~/frozen-throne
    docker:
      - image: golang:1.16
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: "go test ./..."
      - run:
          name: "Build binary "
          command: make build
      - persist_to_workspace:
          root: ~/frozen-throne
          paths:
            - bin/

  deploy_cloud_function:
    working_directory: ~/frozen-throne
    docker:
      - image: circleci/python:3.7
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: "Copy go binary"
          command: mv /tmp/workspace/bin ./bin
      - gcp-cli/install:
          version: "365.0.1"
      - gcp-cli/initialize
      - run:
          name: "Update secrets"
          command: |
            PROJECT_ID=$GOOGLE_PROJECT_ID\
              WRITE_SECRET=$WRITE_SECRET\
              READ_ONLY_SECRET=$READ_ONLY_SECRET\
              WEBHOOK_SECRET=$WEBHOOK_SECRET\
              GITHUB_APP_ID=$GITHUB_APP_ID\
              make update_secrets

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy_cloud_function:
          requires:
            - build
          context:
            - iamevan-me/gcp
          filters:
             branches:
               only: main
